

GET http://localhost:1337/api/software
Accept: application/json

###

POST http://localhost:1337/api/software
Content-Type: application/json
Accept: application/json

{
  "title": "Docker Desktop"
}


###

GET http://localhost:1337/api/software/f12842f1-40a8-4df0-8371-47520b3a9c96
Accept: application/json
