apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: issue-tracker-api-ingress
  labels:
    name: issue-tracker-api-ingress
spec:
  rules:
  - host: api.hypertheory.com
    http:
      paths:
      - pathType: Prefix
        path: "/"
        backend:
          service:
            name: notification-api-service
            port: 
              number: 80

